# Generated by Django 4.2.2 on 2023-06-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0005_alter_commentprofile_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comments',
        ),
        migrations.DeleteModel(
            name='CommentProfile',
        ),
    ]
